def titlescreen():
    print("*" * 80)
    print((("*" + " " * 78 + "*\n") * 11) + ("*" + " " * 78 + "*"))
    # print("*" + " " * 78 + "*")
    print("*" + (" " * 24) + "FUNEMPLOYMENT HEAVY INDUSTRIES" + (" " * 24) + "*")
    print("*" + " " * 78 + "*")
    print("*" + (" " * 35) + "PRESENTS" + (" " * 35) + "*")
    print((("*" + " " * 78 + "*\n") * 10) + ("*" + " " * 78 + "*"))
    # print("*" + " " * 78 + "*")
    print("*" * 80)
